#############################################################################
# Makefile for building: bin/debug/Lorris
# Generated by qmake (2.01a) (Qt 4.6.3) on: so 7 2 12:48:09 2011
# Project:  Lorris.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Lorris.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -Idep/qwt/src -Isrc -Imoc
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -Ldep/qwt/lib -L/usr/lib -lqwt -lQtWebKit -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/mainwindow.cpp \
		src/main.cpp \
		src/HomeTab.cpp \
		src/WorkTab.cpp \
		src/LorrisProbe/lorrisprobe.cpp \
		src/WorkTabMgr.cpp \
		src/WorkTabInfo.cpp \
		src/LorrisProbe/lorrisprobeinfo.cpp \
		src/connection/connectionmgr.cpp \
		src/ui/tabdialog.cpp \
		src/LorrisTerminal/lorristerminal.cpp \
		src/LorrisTerminal/lorristerminalinfo.cpp moc/moc_mainwindow.cpp \
		moc/moc_HomeTab.cpp \
		moc/moc_tabdialog.cpp
OBJECTS       = obj/mainwindow.o \
		obj/main.o \
		obj/HomeTab.o \
		obj/WorkTab.o \
		obj/lorrisprobe.o \
		obj/WorkTabMgr.o \
		obj/WorkTabInfo.o \
		obj/lorrisprobeinfo.o \
		obj/connectionmgr.o \
		obj/tabdialog.o \
		obj/lorristerminal.o \
		obj/lorristerminalinfo.o \
		obj/moc_mainwindow.o \
		obj/moc_HomeTab.o \
		obj/moc_tabdialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Lorris.pro
QMAKE_TARGET  = Lorris
DESTDIR       = bin/debug/
TARGET        = bin/debug/Lorris

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/debug/ || $(MKDIR) bin/debug/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Lorris.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Lorris.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Lorris.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/Lorris1.0.0 || $(MKDIR) obj/Lorris1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/Lorris1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/revision.h src/HomeTab.h src/common.h src/WorkTab.h src/LorrisProbe/lorrisprobe.h src/WorkTabMgr.h src/WorkTabInfo.h src/LorrisProbe/lorrisprobeinfo.h src/connection/connectionmgr.h src/ui/tabdialog.h src/singleton.h src/LorrisTerminal/lorristerminal.h src/LorrisTerminal/lorristerminalinfo.h obj/Lorris1.0.0/ && $(COPY_FILE) --parents src/mainwindow.cpp src/main.cpp src/HomeTab.cpp src/WorkTab.cpp src/LorrisProbe/lorrisprobe.cpp src/WorkTabMgr.cpp src/WorkTabInfo.cpp src/LorrisProbe/lorrisprobeinfo.cpp src/connection/connectionmgr.cpp src/ui/tabdialog.cpp src/LorrisTerminal/lorristerminal.cpp src/LorrisTerminal/lorristerminalinfo.cpp obj/Lorris1.0.0/ && (cd `dirname obj/Lorris1.0.0` && $(TAR) Lorris1.0.0.tar Lorris1.0.0 && $(COMPRESS) Lorris1.0.0.tar) && $(MOVE) `dirname obj/Lorris1.0.0`/Lorris1.0.0.tar.gz . && $(DEL_FILE) -r obj/Lorris1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_mainwindow.cpp moc/moc_HomeTab.cpp moc/moc_tabdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_mainwindow.cpp moc/moc_HomeTab.cpp moc/moc_tabdialog.cpp
moc/moc_mainwindow.cpp: src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o moc/moc_mainwindow.cpp

moc/moc_HomeTab.cpp: src/HomeTab.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/HomeTab.h -o moc/moc_HomeTab.cpp

moc/moc_tabdialog.cpp: src/ui/tabdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/tabdialog.h -o moc/moc_tabdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/HomeTab.h \
		src/WorkTabMgr.h \
		src/singleton.h \
		src/WorkTabInfo.h \
		src/connection/connectionmgr.h \
		src/ui/tabdialog.h \
		src/revision.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o src/mainwindow.cpp

obj/main.o: src/main.cpp src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/HomeTab.o: src/HomeTab.cpp src/HomeTab.h \
		src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/HomeTab.o src/HomeTab.cpp

obj/WorkTab.o: src/WorkTab.cpp src/WorkTab.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/WorkTab.o src/WorkTab.cpp

obj/lorrisprobe.o: src/LorrisProbe/lorrisprobe.cpp src/LorrisProbe/lorrisprobe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/lorrisprobe.o src/LorrisProbe/lorrisprobe.cpp

obj/WorkTabMgr.o: src/WorkTabMgr.cpp src/WorkTabMgr.h \
		src/singleton.h \
		src/WorkTabInfo.h \
		src/connection/connectionmgr.h \
		src/LorrisProbe/lorrisprobeinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/WorkTabMgr.o src/WorkTabMgr.cpp

obj/WorkTabInfo.o: src/WorkTabInfo.cpp src/WorkTabInfo.h \
		src/connection/connectionmgr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/WorkTabInfo.o src/WorkTabInfo.cpp

obj/lorrisprobeinfo.o: src/LorrisProbe/lorrisprobeinfo.cpp src/LorrisProbe/lorrisprobe.h \
		src/LorrisProbe/lorrisprobeinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/lorrisprobeinfo.o src/LorrisProbe/lorrisprobeinfo.cpp

obj/connectionmgr.o: src/connection/connectionmgr.cpp src/connection/connectionmgr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/connectionmgr.o src/connection/connectionmgr.cpp

obj/tabdialog.o: src/ui/tabdialog.cpp src/ui/tabdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tabdialog.o src/ui/tabdialog.cpp

obj/lorristerminal.o: src/LorrisTerminal/lorristerminal.cpp src/LorrisTerminal/lorristerminal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/lorristerminal.o src/LorrisTerminal/lorristerminal.cpp

obj/lorristerminalinfo.o: src/LorrisTerminal/lorristerminalinfo.cpp src/LorrisTerminal/lorristerminal.h \
		src/LorrisTerminal/lorristerminalinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/lorristerminalinfo.o src/LorrisTerminal/lorristerminalinfo.cpp

obj/moc_mainwindow.o: moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o moc/moc_mainwindow.cpp

obj/moc_HomeTab.o: moc/moc_HomeTab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_HomeTab.o moc/moc_HomeTab.cpp

obj/moc_tabdialog.o: moc/moc_tabdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_tabdialog.o moc/moc_tabdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

